name: esg_mate

services:
  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    volumes:
      - ./gateway:/app
    environment:
      - PYTHONUNBUFFERED=1
      - GATEWAY_HOST=0.0.0.0
      - GATEWAY_PORT=8080
      - GATEWAY_RELOAD=false
      - LOG_LEVEL=INFO
    restart: always
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - app-network

volumes:
  redis_data:

networks:
  app-network:
    driver: bridge
