version: '3.8'

services:
  gateway:
    build: .
    container_name: msa-gateway
    ports:
      - "8000:8000"
    environment:
      - GATEWAY_HOST=0.0.0.0
      - GATEWAY_PORT=8000
      - GATEWAY_RELOAD=false
      - LOG_LEVEL=INFO
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - msa-network
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: msa-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - msa-network

  # 예시 마이크로서비스들 (선택사항)
  account-service:
    image: python:3.11-slim
    container_name: account-service
    ports:
      - "8001:8001"
    environment:
      - SERVICE_PORT=8001
    volumes:
      - ./service-examples/account:/app
    working_dir: /app
    command: ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]
    restart: unless-stopped
    networks:
      - msa-network

  chatbot-service:
    image: python:3.11-slim
    container_name: chatbot-service
    ports:
      - "8002:8002"
    environment:
      - SERVICE_PORT=8002
    volumes:
      - ./service-examples/chatbot:/app
    working_dir: /app
    command: ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8002"]
    restart: unless-stopped
    networks:
      - msa-network

volumes:
  redis_data:

networks:
  msa-network:
    driver: bridge
